[package]
name = "unfair_advantage"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.6", features = ["dynamic", "wayland"] }
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
toml = "0.5"
