[[Setup.LymphNode]]
Pos = [-2.0, -2.0]

[[Setup.LymphNode]]
Pos = [2.0, 0.0]

[[Setup.LymphNode]]
Pos = [-2.0, 2.0]

[[Wave]]
StartsAt = 0

[[Wave.Virus]]
Pos = [-1.0, 0.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Rectangle"
Count = 0

[[Wave.Virus]]
Pos = [-2.0, 0.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Semicircle"
Count = 20

[[Wave.Virus]]
Pos = [-3.0, 0.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Triangle"
Count = 20

[[Wave.Virus]]
Pos = [1.0, 0.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Rectangle"
Count = 20

[[Wave.Virus]]
Pos = [2.0, 0.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Semicircle"
Count = 20

[[Wave.Virus]]
Pos = [3.0, 0.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Triangle"
Count = 20
