[[Setup.LymphNode]]
Pos = [-2.0, -2.0]

[[Setup.LymphNode]]
Pos = [2.0, -2.0]

[[Wave]]
StartsAt = 0

[[Wave.Virus]]
Pos = [-2.0, 2.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Rectangle"

[[Wave.Virus]]
Pos = [-1.0, 2.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Rectangle"

[[Wave.Virus]]
Pos = [0.0, 2.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Rectangle"

[[Wave.Virus]]
Pos = [1.0, 2.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Rectangle"

[[Wave.Virus]]
Pos = [2.0, 2.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Rectangle"

[[Wave]]
StartsAt = 1

[[Wave.Virus]]
Pos = [-2.0, 3.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Semicircle"

[[Wave.Virus]]
Pos = [-1.0, 3.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Semicircle"

[[Wave.Virus]]
Pos = [0.0, 3.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Semicircle"

[[Wave.Virus]]
Pos = [1.0, 3.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Semicircle"

[[Wave.Virus]]
Pos = [2.0, 3.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Semicircle"

[[Wave]]
StartsAt = 2

[[Wave.Virus]]
Pos = [-2.0, 4.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Triangle"

[[Wave.Virus]]
Pos = [-1.0, 4.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Triangle"

[[Wave.Virus]]
Pos = [0.0, 4.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Triangle"

[[Wave.Virus]]
Pos = [1.0, 4.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Triangle"

[[Wave.Virus]]
Pos = [2.0, 4.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Triangle"
