[[Setup.LymphNode]]
Pos = [-150.0, -300.0]

[[Setup.LymphNode]]
Pos = [150.0, -300.0]

[[Wave]]
StartsAt = 0

[[Wave.Virus]]
Pos = [-3.0, 2.0]
Vel = [0.0, 0.0]

[[Wave]]
StartsAt = 3

[[Wave.Virus]]
Pos = [0.0, 2.0]
Vel = [0.0, 0.0]

[[Wave]]
StartsAt = 6

[[Wave.Virus]]
Pos = [3.0, 2.0]
Vel = [0.0, 0.0]
