[[Setup.LymphNode]]
Pos = [-4.0, 0.0]

[[Setup.LymphNode]]
Pos = [-1.0, -4.0]

[[Setup.LymphNode]]
Pos = [2.0, 0.0]

[[Wave]]
StartsAt = 10

[[Wave.Virus]]
Pos = [-20.0, 0.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Rectangle"
Count = 50

[[Wave.Virus]]
Pos = [20.0, 0.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Rectangle"
Count = 50

[[Wave]]
StartsAt = 40

[[Wave.Virus]]
Pos = [-20.0, 0.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Rectangle"
Count = 100

[[Wave.Virus]]
Pos = [20.0, 0.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Rectangle"
Count = 100

[[Wave]]
StartsAt = 70

[[Wave.Virus]]
Pos = [-20.0, 0.0]
Vel = [0.0, 0.0]
Body = "Circle"
Antigen = "Rectangle"
Count = 150

[[Wave.Virus]]
Pos = [20.0, 0.0]
Vel = [0.0, 0.0]
Body = "Hexagon"
Antigen = "Rectangle"
Count = 150